"""initial migrate

Revision ID: 650e0293e775
Revises: 
Create Date: 2024-01-31 18:38:51.526713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650e0293e775'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clovers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('founder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['founder_id'], ['users.id'], name=op.f('fk_clovers_founder_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.String(), nullable=True),
    sa.Column('comment_timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('clover_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clover_id'], ['clovers.id'], name=op.f('fk_comments_clover_id_clovers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comments_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userclovers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('clover_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clover_id'], ['clovers.id'], name=op.f('fk_userclovers_clover_id_clovers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_userclovers_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userclovers')
    op.drop_table('comments')
    op.drop_table('clovers')
    op.drop_table('users')
    # ### end Alembic commands ###
